language: python

env:
  global:
    - DB_USERNAME=$RDSNAME
    - DB_PASSWORD=$RDSPW
    - DB_HOST=$RDSHOST

python:
  - "3.7"

install:
   - pip install -r backend/requirements.txt
   - cd frontend && npm install && yarn build && cd ..

script:
  - coverage run backend/manage.py test questions
  - coveralls

before_deploy:
  - cd backend

deploy:
  - provider: elasticbeanstalk
    access_key_id: $ACCESSKEYID
    secret_access_key: $SECRETACCESSKEY
    region: "us-east-1"
    app: $EBAPPNAME
    env: $EBENVNAME
    bucket_name: "elasticbeanstalk-us-east-1-076563148632"
    on:
      repo: gcivil-nyu-org/INET-Wednesday-Spring2023-Team-3
      branch:
        - $BRANCHNAME
  - provider: s3
    access_key_id: $ACCESSKEYID
    secret_access_key: $SECRETACCESSKEY
    bucket: "react-cors-spa-3sovo9yui0"
    local_dir: $TRAVIS_BUILD_DIR/frontend/build
    skip_cleanup: true
    on:
      branch: $BRANCHNAME
